"""Record the reduced-shape Flash-Next MoE fixtures (spec flash-next/02, GitHub #300).

Run from the repository root, on a free GPU (it imports exllamav3's CUDA extension and runs the
transformers router on the card), with the exllamav3 1.5.3 venv and TORCH_CUDA_ARCH_LIST unset:

    F:/ai/ngram-venv/Scripts/python.exe kernel/tests/fixtures/flash_next/record.py

It writes, next to itself:

  trellis_k2.bin, trellis_k2p5.bin, trellis_k3.bin, trellis_k4.bin
      One expert-shaped projection at reduced shape (256 inputs x 128 outputs, 128 tiles of 16x16)
      per K, encoded by exllamav3's own quantizer (quantize_exl3_batch, the converter's path) from a
      synthetic weight and Hessian: its trellis tensor bit for bit (exllamav3's int16
      [in/16][out/16][16 K] layout), the fp16 channel scales suh/svh, and `reconstruct`'s fp16
      output -- the oracle the kernel's trellis decode must equal bit for bit. Also three tokens of
      activations and their fp64 product with the full weight diag(suh) H inner H diag(svh), the
      rotation semantics this script checks against exllamav3's own forward before writing.
  trellis_checksums.bin
      Real-geometry bit-exactness at no fixture cost: for each K and both expert shapes (fused
      gate/up 2560 x 1280, down 640 x 2560), a trellis tensor of counter-hash words (any bit pattern
      is a valid encoding) and a 64-bit checksum of `reconstruct`'s output. The CTest regenerates
      the same words and checksums its own decode.
  router_ref.bin
      The checkpoint's router (transformers' Qwen4ExpTextTopKRouter, BF16 weight and activations,
      as the modeling code runs it) on counter-hash inputs at the real geometry 512 x 2560: its
      BF16 logits, top-10 ids and BF16 weights. The inputs are regenerated by the CTest.
  provenance.json
      Versions, seeds, and what this script measured about the reference (the router's rounding).

ExLlamaV3 is used here as an oracle only (ADR 0043/0044): this script calls its quantizer and
`reconstruct`, and reads nothing of its CUDA sources. The decoder below (`decode_inner`) is the
format's definition written from black-box probes of exllamav3's Python API, and is asserted
bit-exact against `reconstruct` before anything is written.

Container format (IGNFX001), little-endian: the 8-byte magic, then records until EOF, each
  u32 name_len, name (utf-8), u32 dtype, u32 ndim, u64 dims[ndim], u64 nbytes, payload.
dtype codes: 0 u8, 1 i16, 2 u16, 3 i32, 4 f16, 5 bf16 (as u16 bits), 6 f32, 7 f64, 8 u32, 9 u64.
kernel/tests/flash_next_fixture.h reads it.
"""

from __future__ import annotations

import datetime
import json
import math
import os
import struct
import sys
import types

import torch

HERE = os.path.dirname(os.path.abspath(__file__))
DEV = torch.device("cuda:0")

# ---------------------------------------------------------------------------------------------
# Counter hash shared with the C++ tests (kernel/tests/flash_next_fixture.h): lowbias32 of
# (i * 0x9E3779B9 + stream * 0x85EBCA6B) mod 2^32. Vectorized in int64 with explicit masking.

M32 = 0xFFFFFFFF


def lowbias32(x: torch.Tensor) -> torch.Tensor:
    x = x & M32
    x = x ^ (x >> 16)
    x = (x * 0x7FEB352D) & M32
    x = x ^ (x >> 15)
    x = (x * 0x846CA68B) & M32
    x = x ^ (x >> 16)
    return x


def hash_u32(stream: int, n: int) -> torch.Tensor:
    i = torch.arange(n, dtype=torch.int64)
    return lowbias32((i * 0x9E3779B9 + stream * 0x85EBCA6B) & M32)


def hash_uniform(stream: int, n: int, amplitude: float) -> torch.Tensor:
    """float32 in [-amplitude, amplitude): ((h >> 8) * 2^-23 - 1) * amplitude, each step exact or
    one IEEE float32 rounding, as the C++ side computes it."""
    h = hash_u32(stream, n)
    u = (h >> 8).to(torch.float32) * (2.0 ** -23) - 1.0
    return u * torch.tensor(amplitude, dtype=torch.float32)


# ---------------------------------------------------------------------------------------------
# The trellis format, from its definition (probed black-box, asserted against `reconstruct`).
#
# A projection W_inner (in x out, fp16) is stored as tiles of 16 x 16 in exllamav3's int16 tensor
# [in/16][out/16][16 K]. One tile is a bitstream of 256 trellis steps: step p contributes k_p new
# bits (k_p = K; for K = 2.5, 3 bits at odd p and 2 at even p, so 640 bits per tile). The stream
# is big-endian in 32-bit units: stream bit b is bit (31 - b % 32) of the little-endian u32 made
# of int16 words 2(b/32) (low half) and 2(b/32)+1 (high half). Step p's 16-bit state is the 16
# stream bits ending at bit end_p - 1, end_p = k_0 + ... + k_p, read most significant first; the
# window wraps around the tile's stream (tail-biting), so step 0's state ends with the stream's
# last bits. state_p == ((state_{p-1} << k_p) | new_p) & 0xFFFF.
# The value of a state is the mul1 codebook: prod = state * 0x83DCD12D mod 2^32, bsum = sum of
# prod's four bytes, value = fp16(round((1024 + bsum) * fp16(0x1EEE) + fp16(0xC931))), one
# rounding (the product and sum are exact in fp32).
# Step p's value lands at tile element (r, c) with r * 16 + c = TC_PERM[p] (r along `in`, c along
# `out`): lane t of a warp owns steps 8t..8t+7, which are its m16n8k16 B-fragment registers for
# both n8 halves of the tile.

MUL1 = 0x83DCD12D


def tc_perm() -> list[int]:
    perm = [0] * 256
    for t in range(32):
        r0 = (t % 4) * 2
        c0 = t // 4
        rows = [r0, r0 + 1, r0 + 8, r0 + 9]
        for j in range(8):
            r = rows[j % 4]
            c = c0 + (8 if j >= 4 else 0)
            perm[t * 8 + j] = r * 16 + c
    return perm


def steps(K: float) -> list[int]:
    if K == 2.5:
        return [3 if p % 2 == 1 else 2 for p in range(256)]
    assert K in (2, 3, 4)
    return [int(K)] * 256


def words_per_tile(K: float) -> int:
    return int(16 * K)


def mul1_value(states: torch.Tensor) -> torch.Tensor:
    prod = (states.to(torch.int64) * MUL1) & M32
    bsum = (prod & 255) + ((prod >> 8) & 255) + ((prod >> 16) & 255) + ((prod >> 24) & 255)
    k_inv = torch.tensor([0x1EEE], dtype=torch.int16).view(torch.float16).float()
    k_bias = torch.tensor([0xC931 - 0x10000], dtype=torch.int16).view(torch.float16).float()
    return ((1024 + bsum).to(torch.float32) * k_inv.to(states.device) + k_bias.to(states.device)).to(torch.float16)


def decode_states(trellis: torch.Tensor, K: float) -> torch.Tensor:
    tk, tn, W = trellis.shape
    assert W == words_per_tile(K)
    w16 = trellis.view(torch.int16).to(torch.int64) & 0xFFFF
    u32 = w16[..., 0::2] | (w16[..., 1::2] << 16)
    L = W * 16
    b = torch.arange(L, device=trellis.device)
    bits = (u32[..., b // 32] >> (31 - (b % 32))) & 1
    ks = steps(K)
    ends = torch.tensor([sum(ks[: p + 1]) for p in range(256)], device=trellis.device)
    j = torch.arange(16, device=trellis.device)
    idx = (ends.unsqueeze(1) - 16 + j.unsqueeze(0)) % L
    return (bits[..., idx] << (15 - j)).sum(-1)


def decode_inner(trellis: torch.Tensor, K: float) -> torch.Tensor:
    tk, tn, _ = trellis.shape
    vals = mul1_value(decode_states(trellis, K))
    perm = torch.tensor(tc_perm(), device=trellis.device)
    tile = torch.empty_like(vals)
    tile[..., perm] = vals
    return tile.view(tk, tn, 16, 16).permute(0, 2, 1, 3).reshape(tk * 16, tn * 16)


def hadamard128_f64() -> torch.Tensor:
    i = torch.arange(128)
    x = i.unsqueeze(1) & i.unsqueeze(0)
    pc = torch.zeros_like(x)
    for bit in range(7):
        pc += (x >> bit) & 1
    return (1 - 2 * (pc % 2)).to(torch.float64) / math.sqrt(128.0)


def full_weight_f64(inner: torch.Tensor, suh: torch.Tensor, svh: torch.Tensor) -> torch.Tensor:
    """diag(suh) Hb inner Hb diag(svh), Hb = block-diagonal 128-wide Sylvester / sqrt(128)."""
    k, n = inner.shape
    H = hadamard128_f64().to(inner.device)
    w = inner.to(torch.float64)
    w = (H @ w.view(k // 128, 128, n)).view(k, n)
    w = w * suh.to(torch.float64).unsqueeze(1)
    w = (w.view(k, n // 128, 128) @ H).view(k, n)
    return w * svh.to(torch.float64).unsqueeze(0)


# ---------------------------------------------------------------------------------------------
# Container writer.

DT = {torch.uint8: 0, torch.int16: 1, torch.float16: 4, torch.int32: 3, torch.float32: 6, torch.float64: 7}


class Writer:
    def __init__(self, path: str):
        self.path = path
        self.f = open(path, "wb")
        self.f.write(b"IGNFX001")

    def put(self, name: str, t: torch.Tensor, dtype_code: int | None = None):
        t = t.detach().cpu().contiguous()
        code = dtype_code if dtype_code is not None else DT[t.dtype]
        self.put_raw(name, code, list(t.shape), t.numpy().tobytes())

    def put_raw(self, name: str, code: int, dims: list[int], payload: bytes):
        nb = name.encode("utf-8")
        self.f.write(struct.pack("<I", len(nb)) + nb)
        self.f.write(struct.pack("<II", code, len(dims)))
        for d in dims:
            self.f.write(struct.pack("<Q", d))
        self.f.write(struct.pack("<Q", len(payload)))
        self.f.write(payload)

    def put_u16(self, name: str, t: torch.Tensor, code: int):
        """bf16 (5) / u16 (2) payloads from a 16-bit tensor's raw bits."""
        self.put(name, t.contiguous().view(torch.int16), dtype_code=code)

    def close(self):
        self.f.close()


def kname(K: float) -> str:
    return "k2p5" if K == 2.5 else f"k{int(K)}"


# ---------------------------------------------------------------------------------------------
# Fixture 1: reduced-shape projections encoded by exllamav3's quantizer.

RED_IN, RED_OUT = 256, 128
TOKENS = 3


def record_trellis(K: float, prov: dict):
    from exllamav3.ext import exllamav3_ext as ext
    from exllamav3.modules.quant.exl3 import LinearEXL3
    from exllamav3.modules.quant.exl3_lib import quantize as xq

    g = torch.Generator(device="cpu").manual_seed(300 + int(K * 10))
    # A weight with per-row and per-column magnitude structure, and a correlated Hessian, so the
    # quantizer's regularization, LDLQ and scale refit all do real work.
    W = torch.randn(RED_IN, RED_OUT, generator=g) * 0.02
    W *= torch.exp(torch.randn(RED_IN, 1, generator=g) * 0.5)
    W *= torch.exp(torch.randn(1, RED_OUT, generator=g) * 0.3)
    X = torch.randn(4 * RED_IN, RED_IN, generator=g) @ (torch.eye(RED_IN) + 0.1 * torch.randn(RED_IN, RED_IN, generator=g))
    H = (X.T @ X) / X.shape[0]
    hd = {"H": H.to(DEV), "count": 1, "finalized": False, "device": DEV, "L": None, "first_key": f"fixture.{kname(K)}"}
    qa = {"K": K, "devices": [0], "mul1": True, "apply_out_scales": True, "seed": 1000 + int(K * 10)}
    res = xq.quantize_exl3_batch([W.to(DEV)], [hd], [qa])
    ot = res[0][1]
    trellis, suh, svh = ot["trellis"].to(DEV), ot["suh"].to(DEV), ot["svh"].to(DEV)
    assert trellis.dtype == torch.int16 and tuple(trellis.shape) == (RED_IN // 16, RED_OUT // 16, words_per_tile(K))

    recon = torch.empty((RED_IN, RED_OUT), dtype=torch.half, device=DEV)
    ext.reconstruct(recon, trellis, K, False, True)
    mine = decode_inner(trellis, K)
    assert torch.equal(recon.view(torch.int16), mine.view(torch.int16)), f"K={K}: decoder != reconstruct"

    # Activations: BF16-representable values from the counter hash, three tokens.
    x = hash_uniform(stream=7000 + int(K * 10), n=TOKENS * RED_IN, amplitude=2.0).to(torch.bfloat16).float().view(TOKENS, RED_IN)
    w64 = full_weight_f64(recon, suh, svh)
    y64 = x.to(torch.float64).to(DEV) @ w64

    # The rotation semantics, checked against exllamav3's own forward (fp16 internally).
    mul1 = torch.tensor(xq.codebook_mul1_mult, dtype=torch.uint32).view(torch.int).to(DEV)
    lin = LinearEXL3(None, RED_IN, RED_OUT, suh=suh, svh=svh, trellis=trellis, mul1=mul1)
    y_exl = lin.forward(x.half().to(DEV), {"reconstruct": True}).double()
    rel = ((y_exl - y64).abs().max() / y64.abs().max()).item()
    assert rel < 3e-3, f"K={K}: fp64 semantics vs exllamav3 forward rel {rel}"

    path = os.path.join(HERE, f"trellis_{kname(K)}.bin")
    w = Writer(path)
    w.put("K_times_2", torch.tensor([int(K * 2)], dtype=torch.int32))
    w.put("trellis", trellis)
    w.put("suh", suh)
    w.put("svh", svh)
    w.put("reconstruct", recon)
    w.put("x", x)
    w.put("y64", y64)
    w.close()
    prov["trellis"][kname(K)] = {"file": os.path.basename(path), "shape_in_out": [RED_IN, RED_OUT],
                                  "y64_vs_exllamav3_forward_max_rel": rel}
    print(f"K={K}: wrote {path}; y64 vs exllamav3 forward max rel {rel:.2e}")


# ---------------------------------------------------------------------------------------------
# Fixture 2: real-geometry checksums over counter-hash trellis words.

SHAPES = {"gate_up": (2560, 1280), "down": (640, 2560)}


def checksum_u16(values16: torch.Tensor) -> int:
    """sum_i u16[i] * (lowbias32(i) | 1) mod 2^64 over the row-major (in, out) fp16 bits."""
    v = values16.reshape(-1).view(torch.int16).to(torch.int64).cpu() & 0xFFFF
    mult = lowbias32(torch.arange(v.numel(), dtype=torch.int64)) | 1
    prod = v * mult  # < 2^48, exact in int64
    total = 0
    for chunk in prod.split(1 << 20):
        total = (total + int(chunk.sum().item())) % (1 << 64)
    return total


def trellis_words(stream: int, tiles_k: int, tiles_n: int, K: float) -> torch.Tensor:
    n = tiles_k * tiles_n * words_per_tile(K)
    h = hash_u32(stream, n) & 0xFFFF
    return torch.where(h >= 32768, h - 65536, h).to(torch.int16).view(tiles_k, tiles_n, words_per_tile(K))


def record_checksums(prov: dict):
    from exllamav3.ext import exllamav3_ext as ext

    w = Writer(os.path.join(HERE, "trellis_checksums.bin"))
    prov["checksums"] = {}
    for K in (2, 2.5, 3, 4):
        for si, (name, (k, n)) in enumerate(SHAPES.items()):
            stream = 9000 + int(K * 10) * 10 + si
            words = trellis_words(stream, k // 16, n // 16, K).to(DEV)
            recon = torch.empty((k, n), dtype=torch.half, device=DEV)
            ext.reconstruct(recon, words, K, False, True)
            assert torch.equal(recon.view(torch.int16), decode_inner(words, K).view(torch.int16)), f"{name} K={K}"
            cs = checksum_u16(recon)
            key = f"{name}_{kname(K)}"
            w.put_raw(key, 9, [2], struct.pack("<QQ", stream, cs))
            prov["checksums"][key] = {"stream": stream, "checksum": f"{cs:016x}"}
            print(f"{key}: stream {stream} checksum {cs:016x}")
    w.close()


# ---------------------------------------------------------------------------------------------
# Fixture 3: the checkpoint's router on counter-hash inputs, real geometry.

R_TOKENS, R_HIDDEN, R_EXPERTS, R_TOPK = 192, 2560, 512, 10
R_STREAM_X, R_STREAM_W = 101, 202
R_AMP_X, R_AMP_W = 1.7, 0.0346


def record_router(prov: dict):
    from transformers.models.qwen4_exp.modeling_qwen4_exp import Qwen4ExpTextTopKRouter

    torch.backends.cuda.matmul.allow_tf32 = False
    torch.backends.cuda.matmul.allow_bf16_reduced_precision_reduction = False
    cfg = types.SimpleNamespace(num_experts_per_tok=R_TOPK, num_experts=R_EXPERTS, norm_topk_prob=True, hidden_size=R_HIDDEN)
    router = Qwen4ExpTextTopKRouter(cfg).to(DEV, torch.bfloat16)
    x = hash_uniform(R_STREAM_X, R_TOKENS * R_HIDDEN, R_AMP_X).to(torch.bfloat16).view(R_TOKENS, R_HIDDEN).to(DEV)
    W = hash_uniform(R_STREAM_W, R_EXPERTS * R_HIDDEN, R_AMP_W).to(torch.bfloat16).view(R_EXPERTS, R_HIDDEN).to(DEV)
    with torch.no_grad():
        router.weight.copy_(W)
        logits, scores, ids = router(x)
    assert logits.dtype == torch.bfloat16 and scores.dtype == torch.bfloat16

    # How the reference rounds: its BF16 logits against fp32 / fp64 accumulation rounded once.
    l64 = x.double() @ W.double().T
    l32 = x.float() @ W.float().T
    eq64 = (logits == l64.to(torch.bfloat16)).float().mean().item()
    eq32 = (logits == l32.to(torch.bfloat16)).float().mean().item()

    # Selection on the BF16 logits with the lower-index tie rule, against torch's pick.
    lg = logits.float().cpu()
    sorted_vals, order = torch.sort(lg, dim=-1, descending=True, stable=True)  # stable: lower index first on ties
    ours = order[:, :R_TOPK]
    torch_ids = ids.cpu()
    same_set = sum(set(ours[t].tolist()) == set(torch_ids[t].tolist()) for t in range(R_TOKENS))
    same_order = sum(ours[t].tolist() == torch_ids[t].tolist() for t in range(R_TOKENS))
    boundary_ties = int((sorted_vals[:, R_TOPK - 1] == sorted_vals[:, R_TOPK]).sum().item())
    any_ties_in_top = int(sum(len(set(sorted_vals[t, : R_TOPK + 1].tolist())) < R_TOPK + 1 for t in range(R_TOKENS)))

    # Weights: softmax over the ten chosen BF16 logits in fp32, rounded to BF16, against torch's.
    sel = torch.gather(lg, 1, torch_ids)
    p = torch.softmax(sel, dim=-1).to(torch.bfloat16)
    w_equal = (p == scores.cpu()).float().mean().item()

    path = os.path.join(HERE, "router_ref.bin")
    wr = Writer(path)
    wr.put("geometry", torch.tensor([R_TOKENS, R_HIDDEN, R_EXPERTS, R_TOPK, R_STREAM_X, R_STREAM_W], dtype=torch.int32))
    wr.put("amplitudes", torch.tensor([R_AMP_X, R_AMP_W], dtype=torch.float32))
    wr.put_u16("logits", logits.cpu(), code=5)
    wr.put("ids", torch_ids.to(torch.int32))
    wr.put_u16("weights", scores.cpu(), code=5)
    wr.close()
    prov["router"] = {
        "file": os.path.basename(path),
        "module": "transformers.models.qwen4_exp.modeling_qwen4_exp.Qwen4ExpTextTopKRouter",
        "dtypes": {"weight": "bfloat16", "activations": "bfloat16", "logits": str(logits.dtype),
                   "softmax": "float32 over all 512", "weights_out": str(scores.dtype)},
        "logits_equal_bf16_of_fp64_accumulation": eq64,
        "logits_equal_bf16_of_fp32_accumulation": eq32,
        "tokens": R_TOKENS,
        "tokens_with_bf16_tie_at_10th_11th": boundary_ties,
        "tokens_with_any_tie_in_top11": any_ties_in_top,
        "lower_index_rule_same_set_as_torch": same_set,
        "lower_index_rule_same_order_as_torch": same_order,
        "softmax_over_ten_bf16_equal_to_torch_weights": w_equal,
    }
    print(json.dumps(prov["router"], indent=1))


def main():
    assert "TORCH_CUDA_ARCH_LIST" not in os.environ, "unset TORCH_CUDA_ARCH_LIST (it rebuilds exllamav3)"
    import exllamav3
    import transformers
    from exllamav3.version import __version__ as exl3_version

    prov = {
        "recorded_by": "kernel/tests/fixtures/flash_next/record.py",
        "date_utc": datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "exllamav3": exl3_version, "torch": torch.__version__, "transformers": transformers.__version__,
        "device": torch.cuda.get_device_name(0),
        "trellis": {},
    }
    for K in (2, 2.5, 3, 4):
        record_trellis(K, prov)
    record_checksums(prov)
    record_router(prov)
    with open(os.path.join(HERE, "provenance.json"), "w") as f:
        json.dump(prov, f, indent=2, sort_keys=True)
        f.write("\n")


if __name__ == "__main__":
    main()
